name: motos_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0

  # Íconos por defecto de iOS
  cupertino_icons: ^1.0.8

  # Para conectarte al backend
  http: ^1.2.0

  # Animaciones de carga
  flutter_spinkit: ^5.2.0

  # Permite abrir la cámara o galería para seleccionar o tomar fotos
  image_picker: ^1.1.2

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
